### PR TITLE
Using SRS v4.0

### PR DESCRIPTION
**Pull request by PavelKushnirchuk**

### CODE REVIEW

**Comment by skhalymon** [comment]
Need to resolve an issue with HLS playback

**Comment by PavelKushnirchuk** [comment]
> Fixed

**Comment by PavelKushnirchuk** [comment]
> Do we want to keep the println! debug messages about dropping the processes?

No, they are not needed. Fixed

**Review by deiwo — APPROVED** [review]
It seems to work. I don't have any other comments.

**Pull request merged**
